import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Trove',
};

const S = {
  amber: '#ff8c00', border: '#2a2a2a', label: '#888', text: '#ccc', dim: '#666',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '36px' }}>
      <h2 style={{ color: S.amber, fontSize: '11px', letterSpacing: '3px', fontWeight: 'bold', marginBottom: '12px', borderBottom: `1px solid ${S.border}`, paddingBottom: '8px' }}>
        {title}
      </h2>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ color: S.text, fontSize: '13px', lineHeight: 1.9, marginBottom: '12px' }}>{children}</p>;
}

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#000', fontFamily: 'Courier New, monospace', color: S.text }}>
      <nav style={{ borderBottom: `1px solid ${S.amber}`, background: '#000', padding: '0 24px', height: '44px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <a href="/" style={{ background: S.amber, color: '#000', fontWeight: 900, fontSize: '15px', letterSpacing: '3px', padding: '0 14px', height: '44px', display: 'flex', alignItems: 'center', textDecoration: 'none' }}>TROVE</a>
        <span style={{ color: S.label, fontSize: '10px', letterSpacing: '2px' }}>TERMS OF SERVICE</span>
      </nav>

      <div style={{ maxWidth: '800px', margin: '0 auto', padding: '64px 24px' }}>
        <h1 style={{ color: S.amber, fontSize: '20px', letterSpacing: '4px', fontWeight: 900, marginBottom: '8px' }}>TERMS OF SERVICE</h1>
        <p style={{ color: S.dim, fontSize: '10px', letterSpacing: '2px', marginBottom: '48px' }}>LAST UPDATED: MAY 2026</p>

        <Section title="1. ACCEPTANCE OF TERMS">
          <P>By accessing or using Trove ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</P>
        </Section>

        <Section title="2. DESCRIPTION OF SERVICE">
          <P>Trove is a third-party portfolio tracking and analysis tool that aggregates publicly available SEC Form 13F institutional filing data and connects to your brokerage account via OAuth to display portfolio information and facilitate order placement. Trove is not a registered broker-dealer, investment adviser, or financial institution.</P>
        </Section>

        <Section title="3. NOT INVESTMENT ADVICE">
          <P>Nothing on this Service constitutes investment advice, a recommendation to buy or sell any security, or personalized financial advice. All content — including institutional fund data, institutional insights, AI-generated analysis, and portfolio recommendations — is provided for informational purposes only.</P>
          <P>You are solely responsible for your investment decisions. Consult a licensed financial adviser before making any investment decisions.</P>
        </Section>

        <Section title="4. RISK DISCLOSURE">
          <P>Investing in securities involves significant risk, including the possible loss of your entire principal. Past performance of any strategy, fund, or signal does not guarantee future results. Market conditions can change rapidly and without warning.</P>
          <P>Trove does not guarantee the accuracy, completeness, or timeliness of any data displayed. Market data may be delayed. 13F filing data reflects holdings as of the quarter-end date and is filed up to 45 days after that date; fund positions may have changed materially by the time of display.</P>
        </Section>

        <Section title="5. BROKERAGE RELATIONSHIP">
          <P>Trove is an independent third-party application and is not affiliated with, endorsed by, or sponsored by any brokerage firm, including Charles Schwab &amp; Co., Inc., Tastytrade, Inc., or Alpaca Markets, Inc.</P>
          <P>All orders placed through Trove are routed directly to and executed by your connected brokerage. Trove does not hold, custody, or transmit funds. Your brokerage's terms of service and fee schedules govern all transactions. Trove does not add any markup to trades.</P>
        </Section>

        <Section title="6. DATA ACCURACY & THIRD-PARTY SOURCES">
          <P>Trove sources data from the following third-party providers: SEC EDGAR (13F filing data), Polygon.io (market data and news), Anthropic (AI analysis), and your connected brokerage API. Trove makes no warranties about the accuracy or completeness of third-party data.</P>
          <P>AI-generated analysis (bull/bear case, stock summaries) is generated by large language models and may contain errors, omissions, or outdated information. It is not a substitute for your own research.</P>
        </Section>

        <Section title="7. ACCOUNT SECURITY">
          <P>Trove connects to your brokerage via OAuth tokens. Your brokerage credentials (username and password) are never stored by Trove. You are responsible for maintaining the security of your Trove login credentials. Enable two-factor authentication where available. Do not share your login credentials with any third party.</P>
        </Section>

        <Section title="8. LIMITATION OF LIABILITY">
          <P>To the maximum extent permitted by law, Trove and its operators shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to trading losses, data inaccuracies, or service interruptions.</P>
        </Section>

        <Section title="9. MODIFICATIONS">
          <P>Trove reserves the right to modify these Terms at any time. Continued use of the Service after any such changes constitutes your acceptance of the new Terms.</P>
        </Section>

        <Section title="10. GOVERNING LAW">
          <P>These Terms shall be governed by the laws of the United States. Any disputes shall be resolved in the appropriate federal or state courts.</P>
        </Section>
      </div>

      <footer style={{ borderTop: `1px solid ${S.border}`, padding: '24px', textAlign: 'center' }}>
        <div style={{ color: '#333', fontSize: '9px', letterSpacing: '2px' }}>
          © 2026 TROVE &nbsp;·&nbsp;
          <a href="/terms" style={{ color: '#444', textDecoration: 'underline' }}>TERMS</a> &nbsp;·&nbsp;
          <a href="/privacy" style={{ color: '#444', textDecoration: 'underline' }}>PRIVACY</a> &nbsp;·&nbsp;
          <a href="/disclosures" style={{ color: '#444', textDecoration: 'underline' }}>RISK DISCLOSURES</a>
        </div>
      </footer>
    </div>
  );
}
