import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Risk Disclosures — Trove',
};

const S = {
  amber: '#ff8c00', border: '#2a2a2a', label: '#888', text: '#ccc', dim: '#666', red: '#ff4444',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '36px' }}>
      <h2 style={{ color: S.amber, fontSize: '11px', letterSpacing: '3px', fontWeight: 'bold', marginBottom: '12px', borderBottom: `1px solid ${S.border}`, paddingBottom: '8px' }}>
        {title}
      </h2>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ color: S.text, fontSize: '13px', lineHeight: 1.9, marginBottom: '12px' }}>{children}</p>;
}

export default function DisclosuresPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#000', fontFamily: 'Courier New, monospace', color: S.text }}>
      <nav style={{ borderBottom: `1px solid ${S.amber}`, background: '#000', padding: '0 24px', height: '44px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <a href="/" style={{ background: S.amber, color: '#000', fontWeight: 900, fontSize: '15px', letterSpacing: '3px', padding: '0 14px', height: '44px', display: 'flex', alignItems: 'center', textDecoration: 'none' }}>TROVE</a>
        <span style={{ color: S.label, fontSize: '10px', letterSpacing: '2px' }}>RISK DISCLOSURES</span>
      </nav>

      <div style={{ maxWidth: '800px', margin: '0 auto', padding: '64px 24px' }}>
        <h1 style={{ color: S.amber, fontSize: '20px', letterSpacing: '4px', fontWeight: 900, marginBottom: '8px' }}>RISK DISCLOSURES</h1>
        <p style={{ color: S.dim, fontSize: '10px', letterSpacing: '2px', marginBottom: '24px' }}>LAST UPDATED: MAY 2026</p>

        {/* Prominent warning box */}
        <div style={{ background: '#150000', border: `1px solid ${S.red}`, padding: '20px 24px', marginBottom: '48px' }}>
          <p style={{ color: S.red, fontSize: '11px', letterSpacing: '2px', fontWeight: 'bold', marginBottom: '8px' }}>IMPORTANT RISK WARNING</p>
          <p style={{ color: '#cc4444', fontSize: '12px', lineHeight: 1.8, margin: 0 }}>
            Trading and investing in securities involves substantial risk of loss. You may lose some or all of your invested capital.
            Trove does not provide investment advice. The information and tools provided are for informational and educational purposes only.
            You should carefully consider your financial situation and risk tolerance before trading.
          </p>
        </div>

        <Section title="GENERAL INVESTMENT RISK">
          <P>All investments carry risk. The value of securities can go up or down, and you may receive less than you originally invested. There is no guarantee that any investment strategy, signal, or portfolio allocation described or facilitated by Trove will result in profits or prevent losses.</P>
        </Section>

        <Section title="13F DATA LIMITATIONS">
          <P>Form 13F filings are submitted to the SEC up to 45 days after the end of each calendar quarter. By the time 13F data is publicly available, the reported positions may no longer reflect the fund's actual holdings. Institutional investors may have bought, sold, or significantly changed their positions since the filing date.</P>
          <P>13F filings cover only certain categories of securities (primarily U.S.-listed equities and exchange-traded funds). They do not include short positions, options beyond certain thresholds, foreign securities, bonds, or cash. The disclosed long positions represent only a portion of a fund's total portfolio and strategy.</P>
          <P>Institutional buying by large funds does not necessarily indicate that a security will increase in value for retail investors. Institutional strategies, time horizons, and risk tolerances differ substantially from those of retail investors.</P>
        </Section>

        <Section title="AI-GENERATED ANALYSIS">
          <P>Bull case, bear case, and other analytical content generated by Trove's AI features are produced by large language models (Claude by Anthropic). This analysis is generated automatically and has not been reviewed by a licensed financial professional. It may contain errors, omissions, outdated information, or hallucinated data.</P>
          <P>AI analysis does not constitute a recommendation to buy or sell any security and should not be relied upon as the sole basis for any investment decision.</P>
        </Section>

        <Section title="MARKET DATA DELAYS">
          <P>Market data displayed in Trove may be delayed by up to 15 minutes depending on your data provider and subscription. Real-time data availability depends on your brokerage connection. Do not rely solely on Trove's displayed prices for time-sensitive trading decisions.</P>
        </Section>

        <Section title="ORDER EXECUTION RISK">
          <P>Market orders are executed at the best available price at the time of execution, which may differ from the price displayed at the time you placed the order. During periods of high volatility, price movements can be significant. Trove does not guarantee order fills, prices, or execution speed.</P>
          <P>Trove is not a broker-dealer and does not execute orders directly. All orders are routed to and executed by your connected brokerage. Execution quality, speed, and price improvement depend on your broker.</P>
        </Section>

        <Section title="BASKET TRADING RISK">
          <P>Basket orders place multiple individual orders simultaneously. Individual legs of a basket may fill at different prices or times. Some legs may be rejected or partially filled. The total executed value may differ from the estimated value shown.</P>
        </Section>

        <Section title="TECHNOLOGY RISK">
          <P>Trove is a software application subject to technical failures, connectivity issues, and outages. In the event of a system failure, you may be unable to access your account information or place orders through Trove. Always maintain direct access to your brokerage account through official brokerage channels.</P>
        </Section>

        <Section title="NOT A REGISTERED ADVISER">
          <P>Trove and its operators are not registered investment advisers, broker-dealers, or financial planners. No content on this platform should be construed as personalized investment advice. Always consult a qualified financial professional before making investment decisions.</P>
        </Section>
      </div>

      <footer style={{ borderTop: `1px solid ${S.border}`, padding: '24px', textAlign: 'center' }}>
        <div style={{ color: '#333', fontSize: '9px', letterSpacing: '2px' }}>
          © 2026 TROVE &nbsp;·&nbsp;
          <a href="/terms" style={{ color: '#444', textDecoration: 'underline' }}>TERMS</a> &nbsp;·&nbsp;
          <a href="/privacy" style={{ color: '#444', textDecoration: 'underline' }}>PRIVACY</a> &nbsp;·&nbsp;
          <a href="/disclosures" style={{ color: '#444', textDecoration: 'underline' }}>RISK DISCLOSURES</a>
        </div>
      </footer>
    </div>
  );
}
